name: Deploy React App to Shared Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Builds
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest .

      - name: Create container and extract build
        run: |
          # Create a container from the built image
          container_id=$(docker create ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest)
          # Copy the build files from the container to the local filesystem
          docker cp $container_id:/usr/share/nginx/html ./build
          # Clean up the container
          docker rm $container_id

      - name: Deploy using FTP
        if: success()
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: resume/